webapp_tracet/trigger_app/urls.py
from django.conf.urls import url, path
from trigger_app import views

# SET THE NAMESPACE!
app_name = 'basic_app'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
]

webapp_tracet/webapp_tracet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from trigger_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', views.home_page),
    path('user_alert_status/', views.user_alert_status),
    path('user_alert_delete/<int:id>/', views.user_alert_delete),
    path('user_alert_create/', views.user_alert_create),
    path('event_group_log/', views.EventGroupList),
    path('event_group_details/<int:tid>/', views.EventGroup_details),
    path('event_log/', views.EventList),
    path('comet_log/', views.comet_log),
    path('proposal_settings/', views.ProposalSettingsList.as_view()),
    path('proposal_create/', views.proposal_form),
    path('proposal_edit/<int:id>/', views.proposal_form),
    path('proposal_decision_details/<int:id>/', views.ProposalDecision_details),
    path('proposal_decision_result/<int:id>/<int:decision>/',
         views.ProposalDecision_result),
    path('proposal_decision_log/', views.ProposalDecisionList),
    path('proposal_decision_path/<int:id>/', views.proposal_decision_path),
    path('voevent_view/<int:id>/', views.voevent_view),
    path('event_create/', views.event_create),
    path('test_upload_xml/', views.test_upload_xml),
    path('cancel_atca_observation/<str:id>/', views.cancel_atca_observation),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp_tracet/trigger_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage
from django.conf import settings

GRB = 'GRB'
FS = 'FS'
NU = 'NU'
GW = 'GW'
SOURCE_CHOICES = (
    (GRB, 'Gamma-ray burst'),
    (FS, 'Flare star'),
    (NU, 'Neutrino'),
    (GW, 'Gravitational wave'),
)


class Telescope(models.Model):
    name = models.CharField(max_length=64, verbose_name="Telescope name",
                            help_text="E.g. MWA_VCS, MWA_correlate or ATCA.", unique=True)
    lon = models.FloatField(verbose_name="Telescope longitude in degrees")
    lat = models.FloatField(verbose_name="Telescope latitude in degrees")
    height = models.FloatField(
        verbose_name="Telescope height above sea level in meters")

    def __str__(self):
        return f"{self.name}"


class EventTelescope(models.Model):
    name = models.CharField(max_length=64, verbose_name="Event Telescope name",
                            help_text="Telescope that we receive Events from (e.g. SWIFT or Fermi)", unique=True)

    def __str__(self):
        return f"{self.name}"


class TelescopeProjectID(models.Model):
    id = models.CharField(primary_key=True, max_length=64, verbose_name="Telescope Project ID",
                          help_text="The project ID for the telescope used to automatically schedule observations.")
    password = models.CharField(max_length=1024, verbose_name="Telescope Project Password",
                                help_text="The project password for the telescope used to automatically schedule observations.")
    description = models.CharField(
        max_length=256, help_text="A brief description of the project.")
    atca_email = models.CharField(blank=True, null=True, max_length=256, verbose_name="ATCA Proposal Email",
                                  help_text="The email address of someone that was on the ATCA observing proposal. This is an authentication step only required for ATCA.")
    telescope = models.ForeignKey(
        Telescope,
        to_field="name",
        verbose_name="Telescope name",
        help_text="Telescope this proposal will observer with. If the telescope you want is not here add it on the admin page.",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return f"{self.telescope}_{self.id}"


class ProposalSettings(models.Model):
    id = models.AutoField(primary_key=True)
    telescope = models.ForeignKey(
        Telescope,
        to_field="name",
        verbose_name="Telescope name",
        help_text="Telescope this proposal will observer with. If the telescope you want is not here add it on the admin page.",
        on_delete=models.CASCADE,
    )
    project_id = models.ForeignKey(
        TelescopeProjectID,
        to_field="id",
        verbose_name="Project ID",
        help_text="This is the target telescopes's project ID that is used with a password to schedule observations.",
        on_delete=models.CASCADE,
    )
    proposal_id = models.CharField(max_length=16, unique=True, verbose_name="Proposal ID",
                                   help_text="A short identifier of the proposal of maximum lenth 16 charcters.")
    proposal_description = models.CharField(
        max_length=256, help_text="A brief description of the proposal. Only needs to be enough to distinguish it from the other proposals.")
    priority = models.IntegerField(
        help_text="Set proposal processing priority (lower is better)", default=1)

    event_telescope = models.ForeignKey(
        EventTelescope, to_field="name", help_text="The telescope that this proposal will accept at least one Event from before observing. Leave blank if you want to accept all telescopes.", blank=True, null=True, on_delete=models.SET_NULL)
    event_any_duration = models.BooleanField(default=False, verbose_name="Any duration?",
                                             help_text="Will trigger on events with any duration which includes if they have None.")
    event_min_duration = models.FloatField(verbose_name="Min", default=0.256)
    event_max_duration = models.FloatField(verbose_name="Max", default=1.024)
    pending_min_duration_1 = models.FloatField(
        verbose_name="Min", default=1.025)
    pending_max_duration_1 = models.FloatField(
        verbose_name="Max", default=2.056)
    pending_min_duration_2 = models.FloatField(
        verbose_name="Min", default=0.128)
    pending_max_duration_2 = models.FloatField(
        verbose_name="Max", default=0.255)
    maximum_position_uncertainty = models.FloatField(verbose_name="Maximum Position Uncertainty (deg)",
                                                     help_text="A Event must have less than or equal to this position uncertainty to be observed.", default=0.05)
    fermi_prob = models.FloatField(
        help_text="The minimum probability to observe for Fermi sources (it appears to be a percentage, e.g. 50).", default=50)
    swift_rate_signf = models.FloatField(
        help_text="The minimum \"RATE_SIGNIF\" (appears to be a signal-to-noise ratio) to observe for SWIFT sources (in sigma).", default=0.)
    antares_min_ranking = models.IntegerField(
        help_text="The minimum rating (1 is best) to observe for Antares sources.", default=2)
    repointing_limit = models.FloatField(verbose_name="Repointing Limit (deg)",
                                         help_text="An updated position must be at least this far away from a current observation before repointing (in degrees).", default=10.)
    testing = models.BooleanField(
        default=False, help_text="If testing, will not schedule any observations.")
    source_type = models.CharField(
        max_length=3, choices=SOURCE_CHOICES, verbose_name="What type of source will you trigger on?")

    # GW settings
    # GW event property prob
    minimum_neutron_star_probability = models.FloatField(verbose_name="Minimum on the probability that at least one object in the binary has a mass that is less than 3 solar masses",
                                                         help_text="PROB_NS - probability that at least one object in the binary has a mass that is less than 3 solar masses", default=0.01)
    maximum_neutron_star_probability = models.FloatField(verbose_name="Maximum on the probability that at least one object in the binary has a mass that is less than 3 solar masses",
                                                         help_text="PROB_NS - probability that at least one object in the binary has a mass that is less than 3 solar masses", default=1)

    # GW event probs
    minimum_binary_neutron_star_probability = models.FloatField(
        verbose_name="Minimum probability for event to be BNS", help_text="", default=0.01)
    maximum_binary_neutron_star_probability = models.FloatField(
        verbose_name="Maximum probability for event to be BNS", help_text="", default=1)
    minimum_neutron_star_black_hole_probability = models.FloatField(
        verbose_name="Minimum probability for event to be NSBH", help_text="", default=0.01)
    maximum_neutron_star_black_hole_probability = models.FloatField(
        verbose_name="Maximum probability for event to be NSBH", help_text="", default=1)
    minimum_binary_black_hole_probability = models.FloatField(
        verbose_name="Minimum probability for event to be BBH", help_text="", default=0.00)
    maximum_binary_black_hole_probability = models.FloatField(
        verbose_name="Maximum probability for event to be BBH", help_text="", default=1)
    minimum_terrestial_probability = models.FloatField(verbose_name="Minimum probability for event to be terrestial",
                                                       help_text="Limit on the probability that the source is terrestrial (i.e., a background noise fluctuation or a glitch)", default=0.00)
    maximum_terrestial_probability = models.FloatField(verbose_name="Maximum probability for event to be terrestial",
                                                       help_text="Limit on the probability that the source is terrestrial (i.e., a background noise fluctuation or a glitch)", default=0.95)

    # GW custom logic
    observe_low_significance = models.BooleanField(
        verbose_name="Observe events with low significance (high FAR)", default=True, help_text="2/day > FAR > (1/month CBC and 1/year BURST)")
    observe_significant = models.BooleanField(
        verbose_name="Observe events with high significance (low FAR)", default=True, help_text="(1/month CBC and 1/year BURST) > FAR")

    # HESS settings
    minimum_hess_significance = models.FloatField(
        verbose_name="Minimum significance from HESS to trigger an observation", help_text="", default=0.2)
    maximum_hess_significance = models.FloatField(
        verbose_name="Maximum significance from HESS to trigger an observation", help_text="", default=1)

    # MWA settings
    start_observation_at_high_sensitivity = models.BooleanField(verbose_name="Without positional data, start observations with MWA sub array at high sensitivity area",
                                                                default=True, help_text="On early warnings there will not be positional data so start MWA in sub array mode at the high sensitivity area over the indian ocean")
    mwa_freqspecs = models.CharField(default="144,24", max_length=256, verbose_name="MWA frequency specifications",
                                     help_text="The frequency channels IDs for the MWA to observe at.")
    mwa_nobs = models.IntegerField(
        default=1, verbose_name="Number of Observations", help_text="The number of observations to schedule.")
    mwa_exptime = models.IntegerField(default=896, verbose_name="Observation time (s)",
                                      help_text="Exposure time of each observation scheduled, in seconds (must be modulo-8 seconds).")

webapp_tracet/trigger_app/forms.py
# import the standard Django Forms
# from built-in library
from django import forms

import os
from twilio.rest import Client
from twilio.base.exceptions import TwilioRestException

from .models import UserAlerts, ProposalSettings, TelescopeProjectID
from .validators import atca_proposal_id, atca_freq_bands, mwa_proposal_id, mwa_freqspecs, mwa_horizon_limit

account_sid = os.environ.get('TWILIO_ACCOUNT_SID', None)
auth_token = os.environ.get('TWILIO_AUTH_TOKEN', None)
my_number = os.environ.get('TWILIO_PHONE_NUMBER', None)

# creating a form
class UserAlertForm(forms.ModelForm):
    def clean(self):
        if self.cleaned_data['type'] == 1 or self.cleaned_data['type'] == 2:
            # Test that twilio can send a message to the user
            client = Client(account_sid, auth_token)
            try:
                message = client.messages.create(
                        to=self.cleaned_data['address'],
                        from_=my_number,
                        body="This is a test text message from TraceT",
                )
                print(f"MESAGESTART{message}MESSGAEEND")
            except TwilioRestException:
                raise forms.ValidationError("Error sending test text message. Please ensure you have included your area code and verified your number on Twilio as explained in https://tracet.readthedocs.io/en/latest/new_user.html#verifying-your-phone-number-on-twilio")

    # specify the name of model to use
    class Meta:
        model = UserAlerts
        fields = ['proposal', 'type', 'address', 'alert', 'debug', 'approval']


class ProjectSettingsForm(forms.ModelForm):
    def clean(self):
        # Check proposal ID
        if len(self.cleaned_data['proposal_id']) < 6 or self.cleaned_data['proposal_id'] is None:
            raise forms.ValidationError("Please create a proposal ID with at least 6 character")


        # Telescope specific validation
        if 'telescope' in self.cleaned_data.keys():
            telescope = self.cleaned_data['telescope']
            if str(telescope).startswith("MWA"):
                # MWA validation

                # Check the MWA frequency channel specifications are valid
                if self.cleaned_data['mwa_freqspecs']:
                    mwa_freqspecs(self.cleaned_data['mwa_freqspecs'])
                else:
                    raise forms.ValidationError({'mwa_freqspecs': "No Frequency channel Specifications suppled."})

                # Check user selected a horizon limit that won't be rejected by the MWA backend
                mwa_horizon_limit(self.cleaned_data['mwa_horizon_limit'])

            elif str(telescope) == "ATCA":
                # ATCA validation

                # Check user has chosen at least one band
                if not self.cleaned_data['atca_band_3mm'] and not self.cleaned_data['atca_band_7mm'] and \
                   not self.cleaned_data['atca_band_15mm'] and not self.cleaned_data['atca_band_4cm'] and \
                   not self.cleaned_data['atca_band_16cm']:
                    raise forms.ValidationError("Please choose at least 1 ATCA frequency band.")

                # Validate that the user chose ATCA Frequency values within each band
                band1 = self.cleaned_data['atca_band_3mm']
                if band1:
                    # min_freq, max_freq, freq, field_name
                    atca_freq_bands(83000, 105000, self.cleaned_data['atca_band_3mm_freq1'], 'atca_band_3mm_freq1')
                    atca_freq_bands(83000, 105000, self.cleaned_data['atca_band_3mm_freq2'], 'atca_band_3mm_freq2')
                band2 = self.cleaned_data['atca_band_7mm']
                if band2:
                    atca_freq_bands(30000, 50000, self.cleaned_data['atca_band_7mm_freq1'], 'atca_band_7mm_freq1')
                    atca_freq_bands(30000, 50000, self.cleaned_data['atca_band_7mm_freq2'], 'atca_band_7mm_freq2')
                band3 = self.cleaned_data['atca_band_15mm']
                if band3:
                    atca_freq_bands(16000, 25000, self.cleaned_data['atca_band_15mm_freq1'], 'atca_band_15mm_freq1')
                    atca_freq_bands(16000, 25000, self.cleaned_data['atca_band_15mm_freq2'], 'atca_band_15mm_freq2')
                band4 = self.cleaned_data['atca_band_4cm']
                if band4:
                    atca_freq_bands(3900, 11000, self.cleaned_data['atca_band_4cm_freq1'], 'atca_band_4cm_freq1')
                    atca_freq_bands(3900, 11000, self.cleaned_data['atca_band_4cm_freq2'], 'atca_band_4cm_freq2')


    # specify the name of model to use
    class Meta:
        model = ProposalSettings
        fields = '__all__'

class TelescopeProjectIDForm(forms.ModelForm):
    def clean(self):
        # Make sure the project ID is works
        if 'telescope' in self.cleaned_data.keys():
            telescope = self.cleaned_data['telescope']
            if str(telescope).startswith("MWA"):
                mwa_proposal_id(self.cleaned_data['id'], self.cleaned_data['password'])
            elif str(telescope) == "ATCA":
                atca_proposal_id(
                    self.cleaned_data['id'],
                    self.cleaned_data['password'],
                    self.cleaned_data['atca_email'],
                )


    # specify the name of model to use
    class Meta:
        model = TelescopeProjectID
        fields = '__all__'


class TestEvent(forms.Form):
    #xml_file = forms.FileField()
    xml_packet = forms.CharField(max_length=10000, required=False)

webapp_tracet/templates/trigger_app/event_group_details.html
{% extends 'trigger_app/header.html' %}

{% load utils %}

{% block content %}
<title>Event Group Details</title>

<div class="container-sm">
  <h2>{% if event_group.source_type  is not None %} {{ event_group.get_source_type_display }}, {% endif %} Event Group ID {{ event_group.id }}</h2>
  <table class="table-thin">
    <tr>
      <td>Telescope(s)</td>
      <td>{{ telescopes }}</td>
    </tr>
    <tr>
      <td>Trig ID</td>
      <td>{% if event_group.trig_id is not None %}
            {% if 'SWIFT' in telescopes  %}
              <!-- Link to SWIFT telescope page -->
              <a href="https://gcn.gsfc.nasa.gov/other/{{ event_group.trig_id }}.swift" style="text-decoration:None">{{ event_group.trig_id }}</a>
            {% else %}
              {{ event_group.trig_id }}
            {% endif %}
          {% endif %}</td>
    </tr>
    <tr>
      <td>Recieved (UTC)</td>
      <td>{{ event_group.recieved_data|date:"Y-m-d H:i:s" }}</td>
    </tr>
    <tr>
      <td>Earliest Event Observed (UTC)</td>
      <td>{{ event_group.earliest_event_observed|date:"Y-m-d H:i:s" }}</td>
    </tr>
    <tr>
      <td>Latest Event Observed (UTC)</td>
      <td>{{ event_group.latest_event_observed|date:"Y-m-d H:i:s" }}</td>
    </tr>
    <tr>
      <td>Best Right Acension</td>
      <td>{{ event_group.ra_hms }}</td>
    </tr>
    <tr>
      <td>Best Declination</td>
      <td>{{ event_group.dec_dms }}</td>
    </tr>
    <tr>
      {% if poserr_unit is not None and poserr_unit == "deg" %}
        <td>Best Position Error (&#176;)</td>
        <td>{{ event_group.pos_error }}</td>
      {% else %}
        <td>Best Position Error (arcmin)</td>
        <td>{% multiply event_group.pos_error 60 2 %}</td>
      {% endif %}
    </tr>
  </table>
</div>

<div class="container-fluid">
  <h2>Proposal Decisions</h2>
  <table class="fl-table">
    <thead>
      <tr>
        <th>Decision ID</th>
        <th>Proposal Telsecope</th>
        <th>Proposal ID</th>
        <th>Decision</th>
        <th>Decision Reason</th>
        <th>Duration (s)</th>
        <th>RA (HH:MM:SS)</th>
        <th>Dec (DD:MM:SS)</th>
        {% if poserr_unit is not None and poserr_unit == "deg" %}
          <th><a href="?{% url_switch request 'poserr_unit' %}">Position Error (&#176;)</a></th>
        {% else %}
          <th><a href="?{% url_switch request 'poserr_unit' %}">Position Error (arcmin)</a></th>
        {% endif %}
      </tr>
    </thead>
    {% for prop_dec in prop_decs %}
    {% if prop_dec.decision == "I" %}
      <tr class="grey-tr">
    {% else %}
      <tr>
    {% endif %}
      <td><a href="/proposal_decision_details/{{ prop_dec.id }}" style="text-decoration:None">{{ prop_dec.id }}</a</td>
      <td>{{ prop_dec.proposal.telescope }}</td>
      <td>{{ prop_dec.proposal.proposal_id }}</td>
      <td>{{ prop_dec.get_decision_display }}</td>
      <td style="white-space:pre">{{ prop_dec.decision_reason }}</td>
      <td>{{ prop_dec.duration }}</td>
      <td>{{ prop_dec.ra_hms }}</td>
      <td>{{ prop_dec.dec_dms }}</td>
      <td>
      {% if prop_dec.pos_error    is not None %}
        {% if poserr_unit is not None and poserr_unit == "deg" %}
          {{ prop_dec.pos_error }}
        {% else %}
          {% multiply prop_dec.pos_error 60 2 %}
        {% endif %}
      {% endif %}
      </td>
    </tr>
    {% empty %}
    <li>No objects yet.</li>
    {% endfor %}
  </table>


  {% if obs %}
    <h2>Observations</h2>

    <table class="fl-table">
      <thead>
        <tr>
          <th>Observation ID</th>
          <th>Telescope</th>
          <th>Proposal Decision ID</th>
          <th>Proposal</th>
          <th>Proposal ID</th>
          <th>Proposal Project</th>
          <th>Reason</th>
          <th>Cancel Obs?</th>
        </tr>
      </thead>
      <!-- Iterate over object_list -->
      {% for ob in obs %}
      <!-- Display Objects -->
      <tr>
        {% if ob.website_link is None %}
          <td>{{ ob.obsid }}</td>
        {% else %}
          <td><a href="{{ ob.website_link }}" style="text-decoration:None">{{ ob.obsid }}</a></td>
        {% endif %}
        <td>{{ ob.telescope.name }}</td>
        <td><a href="/proposal_decision_details/{{ ob.proposal_decision_id.id }}" style="text-decoration:None">{{ ob.proposal_decision_id.id }}</a</td>
        <td><a href="/proposal_edit/{{ ob.proposal_decision_id.proposal.id }}" style="text-decoration:None">{{ ob.proposal_decision_id.proposal.id }}</a</td>
        <td>{{ ob.proposal_decision_id.proposal.proposal_id }}</td>
        <td>{{ ob.proposal_decision_id.proposal.project_id }}</td>
        <td>{{ ob.reason }}</td>
        <td>
          {% if ob.telescope.name == "ATCA" and ob.proposal_decision_id.decision != 'C' %}
            <button class="btn btn-danger" onclick='var conf = confirm("Are you sure you want to cancel observation {{ ob.obsid }}"); if (conf == true) { window.location = "/cancel_atca_observation/{{ ob.obsid }}";}'>Cancel</button>
          {% endif %}
        </td>
      </tr>
      <!-- If object_list is empty  -->
      {% empty %}
      <p>No observations yet.</p>
      {% endfor %}
    </table>
  {% endif %}

    <h2>Events</h2>

    <table class="fl-table" data-testid="eventgroup">
      <thead>
        <tr>
          <th>Event ID</th>
          <th>Source Type</th>
          <th>Telescope</th>
          <th>Event Type</th>
          <th>Alert Time (UTC)</th>
          <th>Recieved (UTC)</th>
          <th>Trig ID</th>
          <th>Source Name</th>
          <th>Sequence number</th>
          <th>Duration (s)</th>
          <th>RA (HH:MM:SS)</th>
          <th>Dec (DD:MM:SS)</th>
          {% if poserr_unit is not None and poserr_unit == "deg" %}
            <th><a href="?{% url_switch request 'poserr_unit' %}">Position Error (&#176;)</a></th>
          {% else %}
            <th><a href="?{% url_switch request 'poserr_unit' %}">Position Error (arcmin)</a></th>
          {% endif %}
          <th>Fermi Detection Probability (%)</th>
          <th>SWIFT Rate Significance (sigma)</th>
        </tr>
      </thead>
      <!-- Iterate over object_list -->
      {% for event in events %}
      <!-- Display Objects -->
      {% if event.ignored %}
        <tr class="grey-tr">
      {% else %}
        <tr>
      {% endif %}
        <td><a href="/voevent_view/{{ event.id }}" style="text-decoration:None">{{ event.id }}</a></td>
        <td>{% if event_group.source_type  is not None %} {{ event_group.source_type }}  {% endif %}</td>
        <td>{{ event.telescope }}</td>
        <td>{{ event.event_type }}</td>
        <td>{{ event.event_observed|date:"Y-m-d H:i:s" }}</td>
        <td>{{ event.recieved_data|date:"Y-m-d H:i:s" }}</td>
        <td>{% if event.trig_id is not None %}
              {% if 'SWIFT' in telescopes  %}
                <!-- Link to SWIFT telescope page -->
                <a href="https://gcn.gsfc.nasa.gov/other/{{ event_group.trig_id }}.swift" style="text-decoration:None">{{ event_group.trig_id }}</a>
              {% else %}
                {{ event.trig_id }}
              {% endif %}
            {% endif %}</td>
        <td>
          {% if event.source_name is not None %}
          {{ event.source_name }}
          {% elif event_group.source_name is not None %} 
          {{ event_group.source_name }}  
          {% endif %}
        </td>
        <td>{% if event.sequence_num is not None %} {{ event.sequence_num }} {% endif %}</td>
        <td>{% if event.duration     is not None %} {{ event.duration }}     {% endif %}</td>
        <td>{% if event.ra_hms          is not None %} {{ event.ra_hms }}          {% endif %}</td>
        <td>{% if event.dec_dms         is not None %} {{ event.dec_dms }}         {% endif %}</td>
        <td>
        {% if event.pos_error    is not None %}
          {% if poserr_unit == "deg" %}
            {{ event.pos_error }}
          {% else %}
            {% multiply event.pos_error 60 2 %}
          {% endif %}
        {% endif %}
        </td>
        <td>{% if event.fermi_detection_prob is not None %} {{ event.fermi_detection_prob }}  {% endif %}</td>
        <td>{% if event.swift_rate_signif    is not None %} {{ event.swift_rate_signif    }}  {% endif %}</td>
      </tr>
      <!-- If object_list is empty  -->
      {% empty %}
      <li>No objects yet.</li>
      {% endfor %}
      </table>

</div>
{% endblock %}

webapp_tracet/templates/trigger_app/form.html
{% extends 'trigger_app/header.html' %}

{% block title %}{{ page.title }}{% endblock %}

{% block content %}
<div class="container py-4">
    <form action = "" method = "post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value=Submit>
    </form>
</div>
{% endblock %}

webapp_tracet/templates/trigger_app/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if 'ignored' in request.get_full_path %}

            {% if page_obj.has_previous %}
                <a href="{{ request.get_full_path }}&page=">&laquo; first</a>
                <a href="{{ request.get_full_path }}&page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="{{ request.get_full_path }}&page={{ page_obj.next_page_number }}">next</a>
                <a href="{{ request.get_full_path }}&page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}

            {% else %}
                {% if page_obj.has_previous %}
                    <a href="?page=">&laquo; first</a>
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                {% endif %}

        {% endif %}
    </span>
</div>

webapp_tracet/templates/trigger_app/possible_event_association_list.html
{% extends 'trigger_app/header.html' %}

{% block content %}
<title>Possible Event Association Log</title>
<div class="container-fluid">
  <h1>Possible Event Association Log</h1>
  <table class="fl-table">
    <thead>
    <tr>
      <th>ID</th>
      <th>Source Type</th>
      <th>Telescope(s)</th>
      <th>Recieved (UTC)</th>
      <th>Earliest Event Observed (UTC)</th>
      <th>Latest Event Observed (UTC)</th>
      <th>RA (&#176;)</th>
      <th>Dec (&#176;)</th>
      <th>Position Error (&#176;)</th>
    </tr>
    </thead>
    <!-- Iterate over object_list -->
    {% for object, tele_str in object_list %}
    <!-- Display Objects -->
    <tr>
      <td><a href="/possible_event_association_details/{{ object.id }}/" style="text-decoration:None">{{ object.id }}</a></td>
      <td>{% if object.source_type is not None %} {{ object.source_type }}  {% endif %}</td>
      <td>{{ tele_str }}</td>
      <td>{{ object.recieved_data|date:"Y-m-d H:i:s" }}</td>
      <td>{{ object.earliest_event_observed|date:"Y-m-d H:i:s" }}</td>
      <td>{{ object.latest_event_observed|date:"Y-m-d H:i:s" }}</td>
      <td>{{ object.ra }}</td>
      <td>{{ object.dec }}</td>
      <td>{{ object.pos_error }}</td>
    </tr>
    <!-- If object_list is empty  -->
    {% empty %}
    <li>No objects yet.</li>
    {% endfor %}
  </table>

  {% include "trigger_app/pagination.html" %}
</div>
{% endblock %}